FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION

RUN apt-get -qq update && apt-get -qq -y install \
    wget libgomp1

RUN cd /usr/local/bin \
    && wget -q ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-${VERSION}+-x64-linux.tar.gz \
	&& tar -zxvf ncbi-blast-${VERSION}+-x64-linux.tar.gz

ENV PATH="${PATH}:/usr/local/bin/ncbi-blast-2.14.0+/bin"
